In [2]:
# ==================================
# Dash examples
# ==================================

In [3]:
from dash import Dash, html, dcc, callback, Output, Input
import plotly.express as px
import pandas as pd
import polars as pl

In [4]:
# ==================================
# Plot data using Pandas
# ==================================

In [5]:
# Sample dataframe

https://raw.githubusercontent.com/plotly/datasets/master/gapminder_unfiltered.csv

In [6]:
dfa = pd.read_csv('gapminder_unfiltered.csv')

In [7]:
dfa

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
3308     Zimbabwe    Africa  1987   62.351   9216418  706.157306
3309     Zimbabwe    Africa  1992   60.377  10704340  693.420786
3310     Zimbabwe    Africa  1997   46.809  11404948  792.449960
3311     Zimbabwe    Africa  2002   39.989  11926563  672.038623
3312     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[3313 rows x 6 columns]

In [8]:
dfa.country.unique()

<StringArray>
[       'Afghanistan',            'Albania',            'Algeria',
             'Angola',          'Argentina',            'Armenia',
              'Aruba',          'Australia',            'Austria',
         'Azerbaijan',
 ...
      'United States',            'Uruguay',         'Uzbekistan',
            'Vanuatu',          'Venezuela',            'Vietnam',
 'West Bank and Gaza',        'Yemen, Rep.',             'Zambia',
           'Zimbabwe']
Length: 187, dtype: str

In [9]:
dfa[dfa.country=='Zimbabwe']

       country continent  year  lifeExp       pop   gdpPercap
3301  Zimbabwe    Africa  1952   48.451   3080907  406.884115
3302  Zimbabwe    Africa  1957   50.469   3646340  518.764268
3303  Zimbabwe    Africa  1962   52.358   4277736  527.272182
3304  Zimbabwe    Africa  1967   53.995   4995432  569.795071
3305  Zimbabwe    Africa  1972   55.635   5861135  799.362176
3306  Zimbabwe    Africa  1977   57.674   6642107  685.587682
3307  Zimbabwe    Africa  1982   60.363   7636524  788.855041
3308  Zimbabwe    Africa  1987   62.351   9216418  706.157306
3309  Zimbabwe    Africa  1992   60.377  10704340  693.420786
3310  Zimbabwe    Africa  1997   46.809  11404948  792.449960
3311  Zimbabwe    Africa  2002   39.989  11926563  672.038623
3312  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [11]:
app = Dash()

# Requires Dash 2.17.0 or later
app.layout = [
    html.H1(children='Dash app with data (Pandas)', style={'textAlign':'center'}),
    dcc.Dropdown(dfa.country.unique(), 'Canada', id='dropdown-selection'),
    dcc.Graph(id='graph-content')
]

@callback(
    Output('graph-content', 'figure'),
    Input('dropdown-selection', 'value')
)
def update_graph(value):
    dff = dfa[dfa.country==value]
    return px.line(dff, x='year', y='pop')

# Note: if app.run yields an error try changing the server port

if __name__ == '__main__':
    app.run(host="127.0.0.1", port=8051, debug=False)

In [12]:
# ==================================
# Plot data using Polars
# ==================================

In [13]:
# Sample dataframe

https://raw.githubusercontent.com/plotly/datasets/master/gapminder_unfiltered.csv

In [14]:
dfo = pl.read_csv('gapminder_unfiltered.csv')

In [15]:
dfo

shape: (3_313, 6)
┌─────────────┬───────────┬──────┬─────────┬──────────┬────────────┐
│ country     ┆ continent ┆ year ┆ lifeExp ┆ pop      ┆ gdpPercap  │
│ ---         ┆ ---       ┆ ---  ┆ ---     ┆ ---      ┆ ---        │
│ str         ┆ str       ┆ i64  ┆ f64     ┆ i64      ┆ f64        │
╞═════════════╪═══════════╪══════╪═════════╪══════════╪════════════╡
│ Afghanistan ┆ Asia      ┆ 1952 ┆ 28.801  ┆ 8425333  ┆ 779.445314 │
│ Afghanistan ┆ Asia      ┆ 1957 ┆ 30.332  ┆ 9240934  ┆ 820.85303  │
│ Afghanistan ┆ Asia      ┆ 1962 ┆ 31.997  ┆ 10267083 ┆ 853.10071  │
│ Afghanistan ┆ Asia      ┆ 1967 ┆ 34.02   ┆ 11537966 ┆ 836.197138 │
│ Afghanistan ┆ Asia      ┆ 1972 ┆ 36.088  ┆ 13079460 ┆ 739.981106 │
│ …           ┆ …         ┆ …    ┆ …       ┆ …        ┆ …          │
│ Zimbabwe    ┆ Africa    ┆ 1987 ┆ 62.351  ┆ 9216418  ┆ 706.157306 │
│ Zimbabwe    ┆ Africa    ┆ 1992 ┆ 60.377  ┆ 10704340 ┆ 693.420786 │
│ Zimbabwe    ┆ Africa    ┆ 1997 ┆ 46.809  ┆ 11404948 ┆ 792.44996  │
│ Zimbabwe    ┆ Africa    ┆ 2002 ┆ 39.989  ┆ 11926563 ┆ 672.038623 │
│ Zimbabwe    ┆ Africa    ┆ 2007 ┆ 43.487  ┆ 12311143 ┆ 469.709298 │
└─────────────┴───────────┴──────┴─────────┴──────────┴────────────┘

In [16]:
dfo.unique(subset="country")

shape: (187, 6)
┌────────────────────────┬───────────┬──────┬─────────┬───────────┬─────────────┐
│ country                ┆ continent ┆ year ┆ lifeExp ┆ pop       ┆ gdpPercap   │
│ ---                    ┆ ---       ┆ ---  ┆ ---     ┆ ---       ┆ ---         │
│ str                    ┆ str       ┆ i64  ┆ f64     ┆ i64       ┆ f64         │
╞════════════════════════╪═══════════╪══════╪═════════╪═══════════╪═════════════╡
│ Guinea-Bissau          ┆ Africa    ┆ 1952 ┆ 32.5    ┆ 580653    ┆ 299.850319  │
│ Russia                 ┆ FSU       ┆ 1950 ┆ 57.3    ┆ 101936816 ┆ 3674.952691 │
│ Kuwait                 ┆ Asia      ┆ 1952 ┆ 55.565  ┆ 160000    ┆ 108382.3529 │
│ United Kingdom         ┆ Europe    ┆ 1950 ┆ 69.03   ┆ 50127000  ┆ 9766.503753 │
│ Mauritania             ┆ Africa    ┆ 1952 ┆ 40.543  ┆ 1022556   ┆ 743.11591   │
│ …                      ┆ …         ┆ …    ┆ …       ┆ …         ┆ …           │
│ Bosnia and Herzegovina ┆ Europe    ┆ 1952 ┆ 53.82   ┆ 2791000   ┆ 973.533195  │
│ Serbia                 ┆ Europe    ┆ 1952 ┆ 57.996  ┆ 6860147   ┆ 3581.459448 │
│ Moldova                ┆ Europe    ┆ 1950 ┆ 58.4    ┆ 2336432   ┆ 2752.304469 │
│ Madagascar             ┆ Africa    ┆ 1952 ┆ 36.681  ┆ 4762912   ┆ 1443.011715 │
│ Zimbabwe               ┆ Africa    ┆ 1952 ┆ 48.451  ┆ 3080907   ┆ 406.884115  │
└────────────────────────┴───────────┴──────┴─────────┴───────────┴─────────────┘

In [17]:
dfo.filter(pl.col("country")=='Zimbabwe')

shape: (12, 6)
┌──────────┬───────────┬──────┬─────────┬──────────┬────────────┐
│ country  ┆ continent ┆ year ┆ lifeExp ┆ pop      ┆ gdpPercap  │
│ ---      ┆ ---       ┆ ---  ┆ ---     ┆ ---      ┆ ---        │
│ str      ┆ str       ┆ i64  ┆ f64     ┆ i64      ┆ f64        │
╞══════════╪═══════════╪══════╪═════════╪══════════╪════════════╡
│ Zimbabwe ┆ Africa    ┆ 1952 ┆ 48.451  ┆ 3080907  ┆ 406.884115 │
│ Zimbabwe ┆ Africa    ┆ 1957 ┆ 50.469  ┆ 3646340  ┆ 518.764268 │
│ Zimbabwe ┆ Africa    ┆ 1962 ┆ 52.358  ┆ 4277736  ┆ 527.272182 │
│ Zimbabwe ┆ Africa    ┆ 1967 ┆ 53.995  ┆ 4995432  ┆ 569.795071 │
│ Zimbabwe ┆ Africa    ┆ 1972 ┆ 55.635  ┆ 5861135  ┆ 799.362176 │
│ …        ┆ …         ┆ …    ┆ …       ┆ …        ┆ …          │
│ Zimbabwe ┆ Africa    ┆ 1987 ┆ 62.351  ┆ 9216418  ┆ 706.157306 │
│ Zimbabwe ┆ Africa    ┆ 1992 ┆ 60.377  ┆ 10704340 ┆ 693.420786 │
│ Zimbabwe ┆ Africa    ┆ 1997 ┆ 46.809  ┆ 11404948 ┆ 792.44996  │
│ Zimbabwe ┆ Africa    ┆ 2002 ┆ 39.989  ┆ 11926563 ┆ 672.038623 │
│ Zimbabwe ┆ Africa    ┆ 2007 ┆ 43.487  ┆ 12311143 ┆ 469.709298 │
└──────────┴───────────┴──────┴─────────┴──────────┴────────────┘

In [18]:
app = Dash()

# Requires Dash 2.17.0 or later
app.layout = [
    html.H1(children='Dash app with data (Polars)', style={'textAlign':'center'}),
    dcc.Dropdown(dfo["country"].unique().to_list(), 'Canada', id='dropdown-selection'),
    dcc.Graph(id='graph-content')
]

@callback(
    Output('graph-content', 'figure'),
    Input('dropdown-selection', 'value')
)
def update_graph(value):
    dff = dfo.filter(pl.col("country")==value)
    return px.line(dff, x='year', y='pop')

# Note: if app.run yields an error try changing the server port

if __name__ == '__main__':
    app.run(host="127.0.0.1", port=8052, debug=False)

In [19]:
# --------------------------------
# Visualize data in a table using Pandas
# --------------------------------

https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv

In [20]:
# Import packages
from dash import Dash, html
import dash_ag_grid as dag
import pandas as pd

# Incorporate data
dfn = pd.read_csv('gapminder2007.csv')

# Initialize the app
app = Dash()

# App layout
app.layout = [
    html.Div(children='Dash app with data (Pandas)'),
    dag.AgGrid(
        rowData=dfn.to_dict('records'),
        columnDefs=[{"field": i} for i in dfn.columns]
    )
]

# Note: if app.run yields an error try changing the server port

if __name__ == '__main__':
    app.run(host="127.0.0.1", port=8054, debug=False)

In [21]:
# --------------------------------
# Visualize data in a table using Polars
# --------------------------------

https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv

In [23]:
# Import packages
from dash import Dash, html
import dash_ag_grid as dag
import polars as pl

# Incorporate data
dfl = pl.read_csv('gapminder2007.csv')

# Initialize the app
app = Dash()

# App layout
app.layout = [
    html.Div(children='Dash app with data (Polars)'),
    dag.AgGrid(
        rowData=dfl.to_dicts(),
        columnDefs=[{"field": i} for i in dfl.columns]
    )
]

# Note: if app.run yields an error try changing the server port

if __name__ == '__main__':
    app.run(host="127.0.0.1", port=8059, debug=False)